### 打印输出

In [1]:
h = "hello jupyter"
print(h)

a = 3
print("a is:", a)

hello jupyter
a is: 3


### 算术运算

In [7]:
# +-*/%
a = 1 + 3
print("1+3的结果是：", a)
a = 1 - 3
print("1-3的结果是：", a)
a = 1 * 3
print("1*3的结果是：", a)
a = 1 / 3
print("1/3的结果是：", a)
a = 1 % 3
print("1%3的结果是：", a)

# 位运算
b = 1 & 3
print("1&3的结果是：", b)
b = 1 | 3
print("1|3的结果是：", b)
b = 1 ^ 3
print("1^3的结果是：", b)
b = ~3
print("~3的结果是：", b)
b = 1 >> 3
print("1>>3的结果是：", b)
b = 1 << 3
print("1<<3的结果是：", b)

1+3的结果是： 4
1-3的结果是： -2
1*3的结果是： 3
1/3的结果是： 0.3333333333333333
1%3的结果是： 1
1&3的结果是： 1
1|3的结果是： 3
1^3的结果是： 2
~3的结果是： -4
1>>3的结果是： 0
1<<3的结果是： 8


### 基本数据类型

In [12]:
a = 1
print(type(a))  # 自动类型判断 整型

b = 1.0
print(type(b))  # 自动类型判断 浮点型

c = "test"
print(type(c))  # str 字符串类型
c = 'test'
print(type(c))  # str 也可以用单引号

d = True
print(type(d))  # 自动类型判断 布尔型 True False

# 判断是否属于某个类型
isinstance(3.1, int)

<class 'int'>
<class 'float'>
<class 'str'>
<class 'str'>
<class 'bool'>


False

### 条件判断

In [13]:
# f = True
f = False  # 布尔型
if f:  # 后面有冒号
    print("true")  # tab缩进
else:  # 后面有冒号
    print("false")

false


### 循环

In [2]:
for i in range(10): # 后面有冒号，默认从0开始，range参数为终点值，但不包含该值
    print(i, end=" ") # tab缩进

print("")

for i in range(1,10,2): # range中分别为 start，end（不包含），step
    print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 
1 3 5 7 9 

### 函数

In [4]:
def func(a, b):  # 用def来定义函数，后面加冒号
    c = a + b  # tab缩进
    return c


x = 1
y = 2
res = func(x, y)  # 函数调用

print(res)

3


### 导入库

In [5]:
import numpy as np  # 大部分例子用的矩阵库

a = np.ones((3, 3))  # 3x3的矩阵，全为1
print(a)

print(a[0][1])  # 访问矩阵数据

# 矩阵赋值
for j in range(3):
    for i in range(3):
        a[j][i] = i + j
print(a)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
1.0
[[ 0.  1.  2.]
 [ 1.  2.  3.]
 [ 2.  3.  4.]]


### 数据结构

#### 1 列表

In [6]:
lst = []
print(type(lst))

# 添加元素
for i in range(10):
    lst.append(i)
print(lst)

# 删除元素
lst.remove(2)
print(lst)

<class 'list'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 3, 4, 5, 6, 7, 8, 9]


#### 2 集合

In [ ]:
d = {1, 2, 3}
print(type(d), d)

s = set()
print(type(s), s)

# 列表与集合的转换
lst = []
for i in range(10):
    lst.append(i)
lst.append(1)
print("list:", lst)

s = set(lst)
print("set:", s)

# 集合操作，判断某个元素是否在集合中
if 9 in s:
    print("true")
else:
    print("false")

#### 3 字典

In [17]:
d = {}
print(type(d), d)

d['a'] = 1
d['b'] = 2
print(d)

# 遍历字典
for key, val in d.items():
    print(key, ":", val)

# 判断关键字是否在字典中
if 'c' in d:
    print("true")
else:
    print("false")

<class 'dict'> {}
{'a': 1, 'b': 2}
a : 1
b : 2
false


#### 4 元组

In [16]:
t = (1, 2, 3)
print(type(t), t)

# 元组不能动态添加，元组一旦创建不能修改
t.append(4)

<class 'tuple'> (1, 2, 3)


AttributeError: 'tuple' object has no attribute 'append'

### 时间统计

In [14]:
import time  # 导入时间库

start = time.clock()
for i in range(10):
    time.sleep(0.1)  # sleep参数单位为秒
end = time.clock()

print(end - start)

/Users/fengjie/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  This is separate from the ipykernel package so we can avoid doing imports until


0.0019459999999966726


/Users/fengjie/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  


In [3]:
import sys
print(sys.version)

3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]


In [2]:
print 111

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(111)? (<ipython-input-2-99daca9b8a37>, line 1)

In [3]:
from IPython.display import display_html
display_html("""<button onclick="$('.input, .prompt, .output_stderr, .output_error').toggle();">Toggle Code</button>""", raw=True)


Toggle Code

In [5]:
!pip install jupyter_nbextensions_configurator

    100% |████████████████████████████████| 481kB 14kB/s ta 0:00:01
  Running setup.py bdist_wheel for jupyter-nbextensions-configurator ... done
  Stored in directory: /Users/fengjie/Library/Caches/pip/wheels/15/df/fe/2a74fe34709e7fdc5ae153a768675d9fda93cc7d5133ed1fb0
Successfully built jupyter-nbextensions-configurator


In [10]:
!pip install https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tarball/master 

     - 24.8MB 19kB/ss
    100% |████████████████████████████████| 870kB 12kB/s ta 0:00:01
  Running setup.py bdist_wheel for jupyter-contrib-nbextensions ... done
  Stored in directory: /private/var/folders/4q/gq66l7zj5d92l2fxgx_msk2r0000gn/T/pip-ephem-wheel-cache-g1km7192/wheels/22/4a/9f/df59e985684a10ea0e025300581870b5b3a300ee3525f0eef5
  Running setup.py bdist_wheel for jupyter-latex-envs ... done
  Stored in directory: /Users/fengjie/Library/Caches/pip/wheels/0d/71/2a/164491997299b9f2479a251e254323fe35d946779e18f27956
Successfully built jupyter-contrib-nbextensions jupyter-latex-envs


In [11]:
!jupyter contrib nbextension install –user 

jupyter contrib nbextension install takes no extra arguments


In [18]:
!jupyter nbextensions_configurator enable ExecuteTime --user 

jupyter nbextensions_configurator enable takes no extra arguments


In [20]:
!jupyter nbextension enable execute_time/ExecuteTime

Enabling notebook extension execute_time/ExecuteTime...
      - Validating: problems found:
        - require?  X execute_time/ExecuteTime


In [1]:
%config IPCompleter.greedy=True