# 穷举法

穷举法其实是面对很多问题时最容易想到的一种方法，有时显得很笨，但实际上有些问题除了穷举确实没有什么好的办法，所以其实此时使用穷举法并不笨。

但穷举也要讲究策略，不能随机探测，而要按照一定的顺序与方法（比如图的遍历）。

下面举一些例子：


## 1 填数字类型

### 1.1 幻方

最常见的幻方是九宫格，问题定义如下：3x3的格子，象其中填入1-9共9个数字，9个数字不能重复，使得三行三列和两个对角线三个数字的和都相等。

这个问题可以直接用程序穷举如下：

In [7]:
# 9个数，分别为i1-i9，排列顺序如下：
# i1 i2 i3
# i4 i5 i6
# i7 i8 i9
for i1 in range (1,10):
    for i2 in range (1,10):
        for i3 in range (1,10):
            for i4 in range (1,10):
                for i5 in range (1,10):
                    for i6 in range (1,10):
                        for i7 in range (1,10):
                            for i8 in range (1,10):
                                for i9 in range (1,10):
                                    if (i1+i2+i3)==(i4+i5+i6) and (i1+i2+i3)==(i7+i8+i9) and (i1+i2+i3)==(i1+i4+i7) \
                                        and (i1+i2+i3)==(i2+i5+i8) and (i1+i2+i3)==(i3+i6+i9) and (i1+i2+i3)==(i1+i5+i9) \
                                        and (i1+i2+i3)==(i3+i5+i7) and i1 != i2 and i1 != i3 and i1 != i4 and i1 != i5 \
                                        and i1 != i6 and i1 != i7 and i1 != i8 and i1 != i9 and i2 != i3 and i2 != i4 \
                                        and i2 != i5 and i2 != i6 and i2 != i7 and i2 != i8 and i2 != i9 and i3 != i4 \
                                        and i3 != i5 and i3 != i6 and i3 != i7 and i3 != i8 and i3 != i9 and i4 != i5 \
                                        and i4 != i6 and i4 != i7 and i4 != i8 and i4 != i9 and i5 != i6 and i5 != i7 \
                                        and i5 != i8 and i5 != i9 and i6 != i7 and i6 != i8 and i6 != i9 and i7 != i8 \
                                        and i7 != i8 and i7 != i9 and i8 != i9:
                                            print(i1, i2, i3)
                                            print(i4, i5, i6)
                                            print(i7, i8, i9)
                                            print("\n")

2 7 6
9 5 1
4 3 8


2 9 4
7 5 3
6 1 8


4 3 8
9 5 1
2 7 6


4 9 2
3 5 7
8 1 6


6 1 8
7 5 3
2 9 4


6 7 2
1 5 9
8 3 4


8 1 6
3 5 7
4 9 2


8 3 4
1 5 9
6 7 2




这个代码虽然比较长，也很好理解，完全按照题目的意思来写。但运行起来很慢，原因是它做了9的9次方次循环，并且里面的判断很长。

- 如何改进？



       - 首先可以证明三个数的和为15，还可以得到中间的数为5（如何证明？）
    
       - i5确定为5 
    
       - i1 确定后 i9 就确定了，因为i1+i5+i9=15
    
       - 再确定i2，这样，i8也确定了，同时i3，i7，i4，i6也就都确定了
    
       - 所以只需要确定了i2和i9，那么其他的就都能确定了，即只需要两重循环即可

下面就可以利用这两个条件进行代码的简化了：（可能看起来并不直观）

In [8]:
# 9个数，分别为i1-i9，排列顺序如下：
# i1 i2 i3
# i4 i5 i6
# i7 i8 i9
i5 = 5
for i1 in range (1,10):
    for i2 in range (1,10):
        i3 = 15-i1-i2
        i9 = 10-i1
        i8 = 10-i2
        i7 = 15-i8-i9
        i4 = 15-i1-i7
        i6 = 15-i3-i9
        if i3>0 and i3< 10 and i4>0 and i4< 10 and i6>0 and i6< 10 and i7>0 and i7< 10 \
            and i8>0 and i8< 10 and i9>0 and i9< 10 \
            and i1 != i2 and i1 != i3 and i1 != i4 and i1 != i5 \
            and i1 != i6 and i1 != i7 and i1 != i8 and i1 != i9 and i2 != i3 and i2 != i4 \
            and i2 != i5 and i2 != i6 and i2 != i7 and i2 != i8 and i2 != i9 and i3 != i4 \
            and i3 != i5 and i3 != i6 and i3 != i7 and i3 != i8 and i3 != i9 and i4 != i5 \
            and i4 != i6 and i4 != i7 and i4 != i8 and i4 != i9 and i5 != i6 and i5 != i7 \
            and i5 != i8 and i5 != i9 and i6 != i7 and i6 != i8 and i6 != i9 and i7 != i8 \
            and i7 != i8 and i7 != i9 and i8 != i9:
            print(i1, i2, i3)
            print(i4, i5, i6)
            print(i7, i8, i9)
            print("\n")


2 7 6
9 5 1
4 3 8


2 9 4
7 5 3
6 1 8


4 3 8
9 5 1
2 7 6


4 9 2
3 5 7
8 1 6


6 1 8
7 5 3
2 9 4


6 7 2
1 5 9
8 3 4


8 1 6
3 5 7
4 9 2


8 3 4
1 5 9
6 7 2




如果是5x5，7x7或更大的幻方，这种做法就不太好了，需要判断的条件太多。

幻方还有其他有规律的填法，按照这种方法可以将奇数幻方都填出来。步骤如下：

- 1 最上方中间填1
- 2 沿着右上方向填下一个数
    - 如果当前是第一行，则下一个数填到最后一行，如果当前是最后一列，则下一个数填到第一列
    - 如果位置上有值，则填到该数相应位置的下一行
- 3 不断执行2，直到填完数字

这种方法有很多对称模式，因此最终可以填成8组结果，下面的代码是其中一种方式：（解121宫格）

In [22]:
import numpy as np
M = 11
MagicSquare = np.zeros((M,M))
Mid = M>>1
MagicSquare[0][Mid] = 1
i = Mid
j = 0
for idx in range(2, M*M+1):
    i = (i+1)%M
    j = (j-1+M)%M
    if(MagicSquare[j][i]==0):
        MagicSquare[j][i] = idx
    else:
        i = (i-1+M)%M
        j = (j+2)%M
        MagicSquare[j][i] = idx
print(MagicSquare)

[[  68.   81.   94.  107.  120.    1.   14.   27.   40.   53.   66.]
 [  80.   93.  106.  119.   11.   13.   26.   39.   52.   65.   67.]
 [  92.  105.  118.   10.   12.   25.   38.   51.   64.   77.   79.]
 [ 104.  117.    9.   22.   24.   37.   50.   63.   76.   78.   91.]
 [ 116.    8.   21.   23.   36.   49.   62.   75.   88.   90.  103.]
 [   7.   20.   33.   35.   48.   61.   74.   87.   89.  102.  115.]
 [  19.   32.   34.   47.   60.   73.   86.   99.  101.  114.    6.]
 [  31.   44.   46.   59.   72.   85.   98.  100.  113.    5.   18.]
 [  43.   45.   58.   71.   84.   97.  110.  112.    4.   17.   30.]
 [  55.   57.   70.   83.   96.  109.  111.    3.   16.   29.   42.]
 [  56.   69.   82.   95.  108.  121.    2.   15.   28.   41.   54.]]


In [25]:
import numpy as np
M = 5
MagicSquare = np.zeros((M,M))
Mid = M>>1
MagicSquare[0][Mid] = 1
i = Mid
j = 0
for idx in range(2, M*M+1):
    i = (i-1)%M
    j = (j-1+M)%M
    if(MagicSquare[j][i]==0):
        MagicSquare[j][i] = idx
    else:
        i = (i+1+M)%M
        j = (j+2)%M
        MagicSquare[j][i] = idx
print(MagicSquare)

[[ 15.   8.   1.  24.  17.]
 [ 16.  14.   7.   5.  23.]
 [ 22.  20.  13.   6.   4.]
 [  3.  21.  19.  12.  10.]
 [  9.   2.  25.  18.  11.]]


In [33]:
import numpy as np
M = 7
MagicSquare = np.zeros((M,M))
Mid = M>>1
MagicSquare[Mid][0] = 1
i = 0
j = Mid
for idx in range(2, M*M+1):
    i = (i-1)%M
    j = (j-1+M)%M    
    if(MagicSquare[j][i]==0):
        MagicSquare[j][i] = idx
    else:
        i = (i+2)%M
        j = (j+1+M)%M
        MagicSquare[j][i] = idx
print(MagicSquare)

[[ 28.  29.  37.  45.   4.  12.  20.]
 [ 19.  27.  35.  36.  44.   3.  11.]
 [ 10.  18.  26.  34.  42.  43.   2.]
 [  1.   9.  17.  25.  33.  41.  49.]
 [ 48.   7.   8.  16.  24.  32.  40.]
 [ 39.  47.   6.  14.  15.  23.  31.]
 [ 30.  38.  46.   5.  13.  21.  22.]]


In [ ]:
#a b c
#  d
#  e
#  f  

In [40]:
for a in range (1,7):
    for b in range (1,7):
        for c in range (1,7):
            for d in range (1,7):
                for e in range (1,7):
                    for f in range (1,7):
                        if (a+b+c)==(b+d+e+f)and a != b and a != c and a != d and a != e and a != f and b != c \
                        and b != e and b != f and c != d and c != e and c != f and d != e and d != f and e != \
                        f and b != d:
                            print(a, b, c)
                            print(" ", d)
                            print(" ", e)
                            print(" ", f)
                            print("")

2 5 6
  1
  3
  4

2 5 6
  1
  4
  3

2 5 6
  3
  1
  4

2 5 6
  3
  4
  1

2 5 6
  4
  1
  3

2 5 6
  4
  3
  1

4 1 6
  2
  3
  5

4 1 6
  2
  5
  3

4 1 6
  3
  2
  5

4 1 6
  3
  5
  2

4 1 6
  5
  2
  3

4 1 6
  5
  3
  2

4 3 5
  1
  2
  6

4 3 5
  1
  6
  2

4 3 5
  2
  1
  6

4 3 5
  2
  6
  1

4 3 5
  6
  1
  2

4 3 5
  6
  2
  1

5 3 4
  1
  2
  6

5 3 4
  1
  6
  2

5 3 4
  2
  1
  6

5 3 4
  2
  6
  1

5 3 4
  6
  1
  2

5 3 4
  6
  2
  1

6 1 4
  2
  3
  5

6 1 4
  2
  5
  3

6 1 4
  3
  2
  5

6 1 4
  3
  5
  2

6 1 4
  5
  2
  3

6 1 4
  5
  3
  2

6 5 2
  1
  3
  4

6 5 2
  1
  4
  3

6 5 2
  3
  1
  4

6 5 2
  3
  4
  1

6 5 2
  4
  1
  3

6 5 2
  4
  3
  1



### 1.2 数阵图

### 1.3 数字填空

- 若四位数9a8b能被36整除，则这个四位数是多少？

技巧
- 3 各个位数相加和是3的倍数，那么该数字也是3的倍数
- 9 各个位数相加和是9的倍数，那么该数字也是9的倍数
- 1001=7*11*13 从个位开始，三位作为一组，奇数组减偶数组差是7或11或13的倍数，那么该数字也是它的倍数


a17 * 2b = 3cd3

In [2]:
for a in range(1,10):
    for b in range(0, 10):
        for c in range(0, 10):
            for d in range(0,10):
                e = (a*100+17)*(20+b)
                f = 3003+c*100+d*10
                if e == f:
                    print(a,b,c,d)
                    

1 9 3 9


In [ ]:
aa * bb = cde

In [6]:
for a in range(1,10):
    for b in range(1,10):
        for c in range(1,10):
            for d in range(0,10):
                for e in range(0,10):
                    f = (a*11)*(b*11)
                    g = c*100+d*10+e
                    if f == g and c != d and c!= e and d != e and a != b and a != c and a != d and a != e and b != c and b != d and b!= e:
                        print(a,b,c,d,e)
            

        
    


2 4 9 6 8
4 2 9 6 8


## 2 爱因斯坦的思考题